### ISSUE TITLE
Unable to start with Docker

### ISSUE THREAD

**Issue by yodaphone** [Cybrarist/Discount-Bandit#21]
I'm trying to install it via the docker compose file and i get this error

```
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/jupiter/discountbandit/.database.sqlite" to rootfs at "/app/database/database.sqlite": create mount destination for /app/database/database.sqlite mount: cannot mkdir in /var/lib/docker/overlay2/811443d81ed4801caf8caad47f13cf5368d757aff2f8e5b0fb478cac4f7bfbf7/merged/app/database/database.sqlite: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

this is my docker-compose.yml file

```
networks:
  discount-bandit:
    driver: bridge

services:
  discount-bandit:
    build:
      context: .
    image: cybrarist/discount-bandit:v3.1.2-amd64
    ports:
      - 8080:80
    networks:
      - discount-bandit
    volumes:
      - ./database/database.sqlite:/app/database/database.sqlite
      - ./.env:/app/.env
    environment:
      DB_CONNECTION: sqlite
      NTFY_CHANNEL_ID: ""
      TELEGRAM_BOT_TOKEN: ""
      TELEGRAM_CHANNEL_ID: ""
      DEFAULT_USER: "test"
      DEFAULT_EMAIL: "docker@test.com"
      DEFAULT_PASSWORD: "thisismypassword"
      APP_TIMEZONE: UTC
      RSS_FEED: 1
      TOP_NAVIGATION: 0
      DISABLE_TOP_BAR: 0
      BREADCRUMBS: 1
      SPA: 1
      DISABLE_AUTH: 1
      THEME_COLOR: Stone
      APP_URL: "http://localhost:8080"
```

**Comment by Cybrarist** [comment]
did you create the file database.sqlite and .env in your host ?

**Comment by yodaphone** [comment]
I'm using Portainer and using the docker compose contents with web editor

`Failed to deploy a stack: Network discountbandit_discount-bandit Creating Network discountbandit_discount-bandit Created Container discountbandit-discount-bandit-1 Creating Container discountbandit-discount-bandit-1 Created Container discountbandit-discount-bandit-1 Starting Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/data/compose/130/database.sqlite" to rootfs at "/app/database/database.sqlite": create mount destination for /app/database/database.sqlite mount: cannot mkdir in /var/lib/docker/overlay2/5707d29359ed1a0585ddd293b68f83133949063857c01ba537267650f050a2fa/merged/app/database/database.sqlite: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

There no way to create a file in portainer & using these instructions
https://discount-bandit.cybrarist.com/installation/compose-portainer.html

**Comment by Cybrarist** [comment]
if you are using portainer and you want to run the application with sqlite, you can pull the image directly. no need for docker-compose

**Comment by yodaphone** [comment]
> if you are using portainer and you want to run the application with sqlite, you can pull the image directly. no need for docker-compose 

But i followed the instructions on your docs

Can you please LMK how to pull image directly using docker? I was planning on creating a stack so that it's easily manageable

**Comment by tismofied** [comment]
I don't think he has an image to pull from yet. I could be wrong. At the very bottom of his repo page, it says not docker image yet

**Comment by Cybrarist** [comment]
yes, my apologies, didn't have time to update docs, hopefully this weekend.

but anyway, if you are using portainer, you can do the following for v3.1.2-amd64

1-  add the image 

<img width="753" alt="image" src="https://github.com/user-attachments/assets/2ba51485-3d4e-4d83-bc2a-6708230a3eff">


2-  add the desired port and link it to port 80 on container

<img width="1106" alt="port" src="https://github.com/user-attachments/assets/6d283275-542e-46c0-8a28-1fb50a1067e7">

3- add the env variables  and change accordingly
```
DB_CONNECTION=sqlite
NTFY_CHANNEL_ID=""
TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHANNEL_ID=""
DEFAULT_USER="test"
DEFAULT_EMAIL="docker@test.com"
DEFAULT_PASSWORD="thisismypassword"
APP_TIMEZONE=UTC
RSS_FEED=1
TOP_NAVIGATION=0
DISABLE_TOP_BAR=0
BREADCRUMBS=1
SPA=1
DISABLE_AUTH=1
THEME_COLOR=Stone
APP_URL=http://localhost:8080
```

4- deploy the container.
and the app should be working


now if you want to run it using composer, then you need to use the following:
```
services:
  discount-bandit:
    image: cybrarist/discount-bandit:latest-arm
    ports:
      - 8080:80
    environment:
      DB_CONNECTION: sqlite
      NTFY_CHANNEL_ID: ""
      TELEGRAM_BOT_TOKEN: ""
      TELEGRAM_CHANNEL_ID: ""
      DEFAULT_USER: "test"
      DEFAULT_EMAIL: "docker@test.com"
      DEFAULT_PASSWORD: "thisismypassword"
      APP_TIMEZONE: UTC
      RSS_FEED: 1
      TOP_NAVIGATION: 0
      DISABLE_TOP_BAR: 0
      BREADCRUMBS: 1
      SPA: 1
      DISABLE_AUTH: 1
      THEME_COLOR: Stone
      APP_URL: "http://localhost:8080"
```
you don't need volumes as if i am not mistaken, potainer will create one automatically for you that saves all the data.
