### ISSUE TITLE
Improve docker installation experience

### ISSUE THREAD

**Issue by nvllz** [Cybrarist/Discount-Bandit#29]
I wanted to deploy and test your service, but it's a real struggle to find anything about what to do to selfhost it. Looking at other few similar issues I think you could simplify the process, and make it as easy as the quick installation guide of [FreshRSS](https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#quick-run). There's a quick installation command with important options in a single string, and you can specify environment variables as well. Unfortunately I tried to modify the command, but unfortunately it doesn't work for me. Making such deployment tutorial page would allow people to test your app seamlessly. Or just say what to do in one place, as it's stated no docker image for beta in readme.md while the one on dockerhub is not linked. Cheers.

**Comment by Cybrarist** [comment]
Hi there, 

what problem did you face or what command did you run exactly? all attributes are available in docker compose file, so it should just be a matter of passing variables.

as of the readme file, i am aware of the issue and pushing the fix for it with the new version, but you can always refer to docs site as it has the latest info.

**Comment by Cybrarist** [comment]
it should throw an error if you didn't create a "database.sqlite" file along with ".env" file  so the app can use it.

since docker will create volumes as folder and it won't be usable by the application.

**Comment by Cybrarist** [comment]
yea, you are right ( for both points) . i should fix that.

as for the arch problem, i didn't try it before, but i'll check how it can be done if it'll make it easier to install.

**Comment by flintstones-fred** [comment]
I am struggling with docker installation as well. I followed the documentation available on the website. Since I don't want to build from the repo, I am using the docker hub image @Cybrarist has provided. I also "created" the sqlite and .env files so that they are not mounted as directories by docker. But I am still struggling to get the service working as intended. While fetching I get a 500 server error

**Comment by Cybrarist** [comment]
@flintstones-fred are you using docker compose or docker ? 

as there are some environments that you need to pass

**Comment by flintstones-fred** [comment]
@Cybrarist I am using docker-compose. Here is the yaml file I am using  - (changing some details to avoid sharing information)

```
networks:
  discount-bandit:
    driver: bridge
services:
  discount-bandit:
    image: cybrarist/discount-bandit:latest-amd64
    ports:
      - 8040:80
    networks:
      - discount-bandit
    restart: unless-stopped
    volumes:
      - type: bind
        source: /root/discountbandit/database/database.sqlite
        target: /app/database/database.sqlite
      - type: bind
        source: /root/discountbandit/.env
        target: /app/.env
    environment:
      DB_CONNECTION: sqlite
      NTFY_CHANNEL_ID: discount-bandit
      NTFY_BASE_URL: https://ntfy.customdomain.com
      DEFAULT_USER: test
      DEFAULT_EMAIL: test@gmail.com
      DEFAULT_PASSWORD: password
      APPRISE_URL: ""
      APP_TIMEZONE: America/Chicago
      RSS_FEED: 1
      TOP_NAVIGATION: 0
      DISABLE_TOP_BAR: 0
      BREADCRUMBS: 1
      SPA: 1
      DISABLE_AUTH: 1
      THEME_COLOR: Stone
      APP_URL: http://192.168.56.237:8040
      ASSET_URL: http://192.168.56.237:8040
```
