### ISSUE TITLE
Container hangs, on startup

### ISSUE THREAD

**Issue by YouveGotMeowxy** [Cybrarist/Discount-Bandit#37]
I'm trying to give this app a try but having no luck. It always gets to this line:

> Downloading spatie/laravel-feed (4.4.0)

hangs for quite awhile, then the container crashes/stops. Here's my compose, any ideas?

``
  discount-bandit:
    hostname: 'discount-bandit'
    image: 'cybrarist/discount-bandit'
    environment:
      APP_TIMEZONE: 'America/Chicago'
      APP_PORT: '80'
      APP_URL: 'http://discount-bandit:80'
      ASSET_URL: 'http://discount-bandit:80'
      APP_ENV: 'production'
      APP_DEBUG: 'false'
      DB_CONNECTION: 'mysql'
      DB_HOST: 'mariadb'
      DB_DATABASE: 'discountbandit'
      DB_PORT: '3306'
      DB_USERNAME: 'bandit'
      DB_PASSWORD: 'redacted'
      MYSQL_ROOT_PASSWORD: 'redacted' # Why?
      DEFAULT_USER: 'KC'
      DEFAULT_EMAIL: 'domain+bandit@gmail.com'
      DEAFULT_PASSWORD: 'redacted'
      APPRISE_URL: 'apprise'
    networks:
      - 'misc'
      - 'security'
      - 'swag'
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "Discount Bandit"
      swag.uptime-kuma.monitor.url: "https://discountbandit.domain.rocks"
      swag.uptime-kuma.monitor.description: "Best Price Finder"
      swag.uptime-kuma.monitor.parent: "SHOPPING"
    deploy:
      mode: 'replicated'
      replicas: 1
      placement:
        constraints:
          - 'node.labels.Cloud == true'
      restart_policy:
        condition: 'any'
```

**Comment by Cybrarist** [comment]
Hi @YouveGotMeowxy,

it seems that it gets stuck while downloading some packages, can you make sure you have enough space, also check is it timing out or just crashes.


some extra points :
- you don't need to pass port 80 to app_url and asset_url as it's the default for http.
- 'MYSQL_ROOT_PASSWORD' is not needed, where did you get it from ?

**Comment by YouveGotMeowxy** [comment]
Tyvm for such a fast response :)

> it seems that it gets stuck while downloading some packages, can you make sure you have enough space

Plenty of space; I have a 12 TB HDD.

> also check is it timing out or just crashes.

Is there another way for me to be able to tell? All I see in the log is this:

```
^--- etc.

  - Downloading spatie/laravel-health (1.31.0)
  - Downloading shuvroroy/filament-spatie-laravel-health (v2.3.1)
  - Downloading spatie/laravel-feed (4.4.0)
    Container stopped

```

> * 'MYSQL_ROOT_PASSWORD' is not needed, where did you get it from ?

Ok , ty for letting me know. I didn't understand why, since I was already adding the values for the specific database. The is where I saw that, though, right down in the docker compose example:

https://hubgw.docker.com/r/cybrarist/discount-bandit

> some extra points :
> 
> * you don't need to pass port 80 to app_url and asset_url as it's the default for http.

ok, I just also saw that in the example from the link above. I mostly did a copy/paste of the config and just tweaked my system's unique settings.

**Comment by YouveGotMeowxy** [comment]
Another quick question; does this container accept docker secrets in it's compose?

**Comment by YouveGotMeowxy** [comment]
Update: I got it! :D 

Turned out my modem needed a reboot because it was downloading super slow. I've never had that happen before.

I think i may have identified a bug though? my email user name has a plus sign in it, and even though it matches exactly with what I have in my config, it tells me it doesn't recognize it. "These credentials do not match our records."
                          
I also keep seeing this in the log, does it mean anything, or would it help improve anything by setting it in my compose?

> WARN  Please adjust the `OCTANE_SERVER` environment variable.

**Comment by YouveGotMeowxy** [comment]
Also, sorry for so many comments, but while messing with all this I noticed something. Is this logo size intended to be so small? I removed the size restriction and it looks so much better, lol.

![Image](https://github.com/user-attachments/assets/26fe7cbf-1668-4546-afbc-8f794b2d3a2b)

**Comment by YouveGotMeowxy** [comment]
aaaaaand `DISABLE_AUTH: 1` isn't working ...

I still get the login form.

**Comment by Cybrarist** [comment]
hi @YouveGotMeowxy 

 > https://hubgw.docker.com/r/cybrarist/discount-bandit

yea it shouldn't be there, i'll remove it.

>Another quick question; does this container accept docker secrets in it's compose?

i didn't try tbh so i guess not.

>I think i may have identified a bug though? my email user name has a plus sign in it, and even though it matches exactly with what I have in my config, it tells me it doesn't recognize it. "These credentials do not match our records."

yea, i guess it might cause an issue since i add the user as command, didn't really think someone might use + in email, but i'll add a fix for it as i think wrapping it with "" should be enough.

https://github.com/Cybrarist/Discount-Bandit/blob/a91a9ba86a583c8ef21fb0e29584799802e90204/docker/entrypoint.sh#L35C78-L35C86

>I also keep seeing this in the log, does it mean anything, or would it help improve anything by setting it in my compose?

i'll investigate further to see if there's a way i can get rid of it.

>and 2.6 GB is a lot of memory for a container to eat up

yes, please disable all stores that you don't need from the the system, then restart the container, so the container won't create supervisors for the stores that are disabled.

i thought i have put this info on the website, but apparently i didn't, so i will add it later. but that should reduce the ram usage.

>Is this logo size intended to be so small? 
yea this is the default, so it doesn't really matter to me tbh. it's just a logo in the end :D

>DISABLE_AUTH: 1 isn't working ...
hmmm, i assume you restarted the container after you passed the env or after you edited it, right ? and of course you are using the latest.

**Comment by YouveGotMeowxy** [comment]
> hmmm, i assume you restarted the container after you passed the env or after you edited it, right ? and of course you are using the latest.

Yes, the latest, and I've restarted the container several times and it still shows up. I also still can't login, even when I remove the plus sign from my email address. Any idea on that?

For shits n grins I optimized the logo as well if you want to use it. trimmed off about 12kb

![Image](https://github.com/user-attachments/assets/ca920db3-3767-4f54-8fa6-7489edc7ae85)

**Comment by Cybrarist** [comment]
ok, i'll double check it.

can you send me the log you are getting when you start the container with the email that doesn't contain '+' please

**Comment by YouveGotMeowxy** [comment]
@Cybrarist Here's the entire log I have (the email is on line 87): https://pastebin.com/s7rgUF94

the pw doesn't seem to matter. For a test case I even just set it to 1234567890.

Here's the entire compose I'm using:

<details>
  <summary>Expand</summary>

  ```
    discount-bandit:
    hostname: 'discount-bandit'
    image: 'cybrarist/discount-bandit'
    environment:
      APP_TIMEZONE: 'America/Chicago'
      APP_PORT: '443'
      APP_URL: 'https://discount-bandit.domain.rocks'
      ASSET_URL: 'https://discount-bandit.domain.rocks'
      APP_ENV: 'production'
      APP_DEBUG: 'false'
      DB_CONNECTION: 'mysql'
      DB_HOST: 'mariadb'
      DB_DATABASE: 'discountbandit'
      DB_PORT: '3306'
      DB_USERNAME: 'bandit'
      DB_PASSWORD: 'redacted'
      DEFAULT_USER: 'KC'
      DEFAULT_EMAIL: 'tichondriusgirl@gmail.com'
      DEAFULT_PASSWORD: '1234567890'
      THEME_COLOR: 'Stone'
      #DISABLE_AUTH: 1 # For Authelia/Authentik (doesn't work)
      APPRISE_URL: 'apprise'
    networks:
      - 'mariadb'
      - 'misc'
      - 'security'
      - 'swag'
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "Discount Bandit"
      swag.uptime-kuma.monitor.url: "https://discountbandit.domain.rocks"
      swag.uptime-kuma.monitor.description: "Best Price Finder"
      swag.uptime-kuma.monitor.parent: "SHOPPING"
    deploy:
      mode: 'replicated'
      replicas: 1
      placement:
        constraints:
          - 'node.labels.Cloud == true'
      restart_policy:
        condition: 'any'
  ```

</details>
