### ISSUE TITLE
unRAID app

### ISSUE THREAD

**Issue by FunkyMuse** [Cybrarist/Discount-Bandit#65]
this is a cool project, have you considered adding it to the unRAID app catalog?

**Comment by Cybrarist** [comment]
Hi @FunkyMuse 

i tried to setup unraid and build one, but i got multiple errors then i forgot about it tbh. hopefully i will do it with the next major version unless someone is willing to help to make it for the current one.

**Comment by FunkyMuse** [comment]
> Hi [@FunkyMuse](https://github.com/FunkyMuse)
> 
> i tried to setup unraid and build one, but i got multiple errors then i forgot about it tbh. hopefully i will do it with the next major version unless someone is willing to help to make it for the current one.

I tried and failed too, was unable to get the container open the web ui :/

**Comment by Cybrarist** [comment]
sure, can you share me your discord or add me from the server so we can discuss it if it's ok with you.

**Comment by FunkyMuse** [comment]
> sure, can you share me your discord or add me from the server so we can discuss it if it's ok with you.

https://discord.gg/EsUQpV93

**Comment by FunkyMuse** [comment]
For those wondering, i'm using dockge to manage this app

```yaml
services:
  discount-bandit:
    image: cybrarist/discount-bandit:latest
    container_name: discount-bandit
    ports:
      - 8133:80
    environment:
      NOTIFY_ON_ANY_PRICE_CHANGE: false
      DB_CONNECTION: sqlite
      NTFY_CHANNEL_ID: ""
      NTFY_BASE_URL: ""
      TELEGRAM_BOT_TOKEN: ""
      TELEGRAM_CHANNEL_ID: ""
      DEFAULT_USER: test
      DEFAULT_EMAIL: docker@test.com
      DEFAULT_PASSWORD: thisismypassword
      APPRISE_URL: ""
      APP_TIMEZONE: Europe/Skopje
      RSS_FEED: 1
      TOP_NAVIGATION: 0
      DISABLE_TOP_BAR: 0
      BREADCRUMBS: 1
      SPA: 1
      #DISABLE_AUTH: 0
      THEME_COLOR: Stone
      APP_URL: your_url
      ASSET_URL: same as app_url
    volumes:
      - ./database/database.sqlite:/app/database/database.sqlite
      - ./logs:/logs
    networks:
      - discount-bandit
networks:
  discount-bandit:
    driver: bridge
```

and make sure you create database.sqlite in dockge's discount-bandit folder under database/database.sqlite
