### ISSUE TITLE
Not receiving Gotify Notifications

### ISSUE THREAD

**Issue by thebigjoe1** [Cybrarist/Discount-Bandit#66]
I have gotify setup for notifications, and have set notifications to alerty me on any price change. I have validated my Gotify BASE URL and TOKEN. I have also tired with setting price variations within the products i watch and still do not receive any notications. 

Below is my current docker-compose file. Let me know if there is anything else i can provide to assist in troubleshooting: 

```
 services:
  discount-bandit:
    image: cybrarist/discount-bandit:latest
    container_name: discount-bandit
    ports:
      - 8133:80
    env_file:
      - ./stack.env
    environment:
      NOTIFY_ON_ANY_PRICE_CHANGE: true
      DB_CONNECTION: sqlite
      GOTIFY_BASE_URL: ${GOTIFY_BASE_URL}
      GOTIFY_TOKEN: ${GOTIFY_TOKEN}
      DEFAULT_USER: ${DEFAULT_USER}
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      APP_TIMEZONE: America/New_York
      RSS_FEED: 1
      TOP_NAVIGATION: 0
      DISABLE_TOP_BAR: 0
      BREADCRUMBS: 1
      SPA: 1
      #DISABLE_AUTH: 0
      THEME_COLOR: Stone
      APP_URL: ${APP_URL}
      ASSET_URL: ${APP_URL}
    volumes:
     - /opt/docker-apps/discount-bandit/database/database.sqlite:/app/database/database.sqlite #"touch database.sqlite" to create folder before deploying stack
     - /opt/docker-apps/discount-bandit/logs:/logs
    networks:
      - discount-bandit
networks:
  discount-bandit:
    driver: bridge
```
